language: php

php:
    - "5.6"
    - "7.0"

before_script:
    - composer install
    - composer require satooshi/php-coveralls

after_success:
    - travis_retry php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar
    - >-
        travis_retry php ocular.phar code-coverage:upload --format=php-clover
        build/logs/clover.xml
